### ISSUE TITLE
Fail everytime turbo degrades 

### ISSUE THREAD

**Issue by nicolai11111** [renzuzu/renzu_turbo#11]
![image](https://user-images.githubusercontent.com/127895837/228929928-2032fe2a-56fd-4c4a-a189-93151957f466.png)

When installing turbo in tuners menu (forced induction) It doesent show as installed, but it works. 
When driving afterwards i get errors alot in server console.

**Comment by nicolai11111** [comment]
The error come each time the BOV whistles actually.

**Comment by renzuzu** [comment]
This is fixed in latest version.
